allowBuilds:
  vue-demi: false
minimumReleaseAgeExclude:
  - "@cfasim-ui/charts@0.8.12"
  - "@cfasim-ui/components@0.8.12"
  - "@cfasim-ui/pyodide@0.8.12"
  - "@cfasim-ui/shared@0.8.12"
  - "@cfasim-ui/theme@0.8.12"
  - "@cfasim-ui/wasm@0.8.12"
  - cfasim-ui@0.8.12
